<div class="footer-container">
    <footer class="footer">
        <ul class="footer-left">
            <li>© 2017 Train Team Blog </li>
        </ul>
        <ul class="footer-right">
            <li><a href="#">Contact Us</a></li>
            <li><a href="https://twitter.com/" target="_blank"><img src="images/twitter.png" alt="twitter" width="15"/></a></li>
            <li><a href="https://facebook.com"><img src="images/facebook.png" alt="facebook" width="15"/></a></li>
            <li><a href="https://instagram.com"><img src="images/instagram.png" alt="instagram" width="15"/></a></li>
            <li><a href="https://youtube.com"><img src="images/youtube.png" alt="youtube" width="15"/></a></li>
        </ul>
    </footer>
</div>
</body>
</html>
