<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Movies On The Train Blog</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada" rel="stylesheet">
        <link rel="stylesheet" href="blog_css.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body> 
        <header>
            <div class="container container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand blog-name">Movies On The Train Blog</a>
                </div>

                <ul class="nav navbar-nav">
                    <?php
                    session_start();
                    if (!empty($_SESSION['login_user'])) {

                        if ($_SESSION['roleID'] == '1') {
                            
                            echo "<li class='nav-links'><a href='movie.php'>Add Movie Blog</a></li>";
                          //  echo "<li class='nav-links'><a href='blogs.php?blog'>Add Blog</a></li>";
                            echo "<li class='nav-links'><a href='delete.php?delete'>Delete User</a></li>";
                        }
                        echo "<li class='nav-links'><a href='index.php'>Home</a></li>";
                        echo "<li class='nav-links'><a href='about_page.php'>About</a></li>";
                        echo "<li class='nav-links'><a href='search.php?search'>Search</a></li>";
                        echo "<li class='nav-links'><a href='comp.php?competition'>Competition</a></li>";
                        echo "<li class='nav-links'><a href='viewcategory.php?id'>Categories</a></li>";
                        echo "<li style='color:red;text-transform: capitalize;' class='nav-links'>" . "May the Force be with you " . $_SESSION['login_user'] . " </style></a></li>";
                        echo "</ul>";
                        echo "<ul class='nav navbar-nav navbar-right'>";
                        echo "<li class='nav-links'><a href='logout.php'><span class='glyphicon glyphicon-log-in'></span> Sign out</a></li>";
                        echo "</ul>";
                        echo "</div>";
                    } elseif
                    (empty($_SESSION['login_user'])) {
                        echo "<li class='nav-links'><a href='index.php'>Home</a></li>";
                        echo "<li class='nav-links'><a href='about_page.php'>About</a></li>";
                        echo "<li class='nav-links'><a href='viewcategory.php?id'>Categories</a></li>";
                        echo "<li class='nav-links'><a href='search.php?search'>Search</a></li>";
                        echo "</ul>";
                        echo "<ul class='nav navbar-nav navbar-right'>";
                        echo "<li class='nav-links'><a href='signup.php'><span class='glyphicon glyphicon-log-in'></span> Sign up</a></li>";
                        echo "<li class='nav-links'><a href='login.php'><span class='glyphicon glyphicon-log-in'></span> Sign in</a></li>";
                        echo "</ul>";
                        echo "</div>";
                    }
                    ?>

                    </header>


