<style>
    form {
        text-align: center;
    }
</style>
<form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">

    <h4>You sure you want to delete a user?</h4>

    <p><label for="username"></label><br />
        <input name="username" type="text" pattern=".{6,30}" required title="must be greater than 6 characters" placeholder="Username";/>

    <p><input type="submit" name="submit" value='Delete User'></p>

</form>