<form action="" method="post">

    <p><label>Name</label><br />
        <input type="text" name="name" required=""/></p>

    <p><label>Year</label><br />
        <input type="year" name="year" required=""/></p>

    <p><label>Certificate</label><br />
        <input type="text" name="certificate" required=""/></p>

    <p><label>runTime</label><br />
        <input type="text" name="runTime" required=""/></p>

    <p><label>Image</label><br />
        <input type="text" name="image" required=""/></p>

    <p><input type="submit" name="submit" value="Submit" required=""></p>

</form>

