<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="blog_css.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <div class="nav-background">
        <div class="row">
            <div class="col-xs-12">
                <ul class="footer">
                    <li>Follow Us</li>
                    <li class="fa fa-twitter"><a href="twitter.com">twitter</a></li>
                    <li class="fa fa-facebook"><a href="facebook.com">facebook</a></li>
                    <li class="fa fa-instagram"><a href="instagram.com">instagram</a></li>
                </ul>
            </div>
        </div>

    </div>
</body>
</html>
