<style>
    form {
        text-align: center;
    }
</style>
<form action="login.php" method="post">

    <h4>Sign in</h4>
    <div>
        <p>  <label for="username">Username: </label><br />
            <input name="username" type="text"/>
    </div>

    <div>
        <p> <label for="password">Password: </label><br />
            <input name="password" type="password"/>
    </div>

    <button type="submit">Sign in</button>
</form>

